Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.hostname = 'web'
  config.vm.box_url = "ubuntu/precise64"

  config.vm.network :private_network, ip: "192.168.56.101"

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--memory", 512]
    v.customize ["modifyvm", :id, "--name", "web"]
  end
end
